resources:
  containers:
  - container: linux
    image: jaci/azure-native-linux:2018.12.06
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:18.04

jobs:
- job: windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-init.yml
  - template: azure-steps.yml
    parameters:
      args: '-Pno-roborio'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: azure-init.yml
  - template: azure-steps.yml
    parameters:
      args: '-Pno-roborio'

- job: linux
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - template: azure-steps.yml
    parameters:
      args: '-Pno-roborio'

- job: roborio
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: wpilib2019
  steps:
  - template: azure-steps.yml
    parameters:
      args: '-xcheck'

- job: pi
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: raspbian
  steps:
  - template: azure-steps.yml
    parameters:
      args: '-Pno-roborio -xcheck'

- job: tinkerboard
  pool:
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: ':vision:installTinkerboardToolchain'
      options: '-Pno-roborio --scan --stacktrace'
  - template: azure-steps.yml
    parameters:
      args: '-Pno-roborio'